[[plugins]]
# Gitの変更行の視覚化
repo ='airblade/vim-gitgutter'

[[plugins]]
# Uniteからrailsプロジェクトの移動を簡単にできるようにする
repo ='basyura/unite-rails'

[[plugins]]
# toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
# utility for go
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]]
# migemo用プラグイン(要 brew install cmigemo)
repo = 'haya14busa/vim-migemo'

[[plugins]]
# ステータスラインをいい感じにしてくれるプラグイン
repo = 'itchyny/lightline.vim'

[[plugins]]
# coffee scriptをいい感じに編集できるプラグイン"
repo = 'kchmck/vim-coffee-script'

[[plugins]]
repo = 'kyoz/purify'
rtp = 'vim'

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
# インデントに色を付けて見やすくする
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'posva/vim-vue'

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
# コード補完
repo ='Shougo/ddc.vim'

[[plugins]]
# コード補完
repo ='Shougo/ddc-around'

[[plugins]]
# コード補完
repo ='Shougo/ddc-matcher_head'

[[plugins]]
# コード補完
repo ='Shougo/ddc-sorter_rank'

[[plugins]]
# Unite.vimで最近使ったファイルを表示できるようにする
repo ='Shougo/neomru.vim'

[[plugins]]
# ヤンクのヒストリーを管理できるプラグイン
repo ='Shougo/neoyank.vim'

[[plugins]]
# ファイルオープンを便利に
repo ='Shougo/unite.vim'

[[plugins]]
# ファイラー
repo ='Shougo/vimfiler'

[[plugins]]
# vim上でshellを動かすためのユーティリティ
repo ='Shougo/vimproc.vim'
build = 'make'

[[plugins]]
# 自動的に閉じ括弧を挿入してくれるプラグイン
repo ='Townk/vim-autoclose'

[[plugins]]
# Ruby向けにendを自動挿入してくれるプラグイン
repo ='tpope/vim-endwise'

[[plugins]]
# Gitを便利に使うプラグイン
repo ='tpope/vim-fugitive'

[[plugins]]
# 文字列を何かでくくったり解除したりするプラグイン
repo ='tpope/vim-surround'

[[plugins]]
# コード補完
repo ='vim-denops/denops.vim'

[[plugins]]
# grepを可能にするプラグイン
repo ='vim-scripts/grep.vim'

[[plugins]]
# rubocop自動実行プラグイン
repo ='w0rp/ale'

[[plugins]]
# SQLのfomat用プラグイン
repo ='yukimura1227/fmtsql.vim'
