[[plugins]]
# Gitを便利に使うプラグイン
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'kyoz/purify'
rtp = 'vim'

[[plugins]]
# ステータスラインをいい感じにする
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'
