[[plugins]]
# Gitの変更行の視覚化
repo ='airblade/vim-gitgutter'

[[plugins]]
repo = 'catppuccin/vim'

[[plugins]]
# rubocopなどを自動実行するためのプラグイン
repo = 'dense-analysis/ale'

[[plugins]]
repo = 'elzr/vim-json'

# [[plugins]]
# repo = 'junegunn/fzf'
# build_on = '''
# ./install -all
# '''

[[plugins]]
repo = 'junegunn/fzf.vim'

[[plugins]]
# Gitを便利に使うプラグイン
repo = 'tpope/vim-fugitive'

[[plugins]]
# 文字列を何かでくくったり解除したりするプラグイン
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'mattn/vim-maketable'

[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
# Ruby向けにendを自動挿入してくれるプラグイン
repo = 'tpope/vim-endwise'

[[plugins]]
# ステータスラインをいい感じにする
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
# インデントに色を付けて見やすくする
repo = 'Yggdroot/indentLine'
