[[plugins]]
# Gitの変更行の視覚化
repo ='airblade/vim-gitgutter'

[[plugins]]
# rubocopなどを自動実行するためのプラグイン
repo = 'dense-analysis/ale'

[[plugins]]
# Gitを便利に使うプラグイン
repo = 'tpope/vim-fugitive'

[[plugins]]
# 文字列を何かでくくったり解除したりするプラグイン
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'kyoz/purify'
rtp = 'vim'

[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
# コード補完
repo ='Shougo/ddc.vim'

[[plugins]]
# UI framework
repo ='Shougo/ddu.vim'

[[plugins]]
repo ='Shougo/ddu-commands.vim'

[[plugins]]
repo ='Shougo/ddu-filter-matcher_substring'

[[plugins]]
repo ='Shougo/ddu-kind-file'

[[plugins]]
repo ='Shougo/ddu-source-file'

[[plugins]]
repo ='Shougo/ddu-source-file_rec'

[[plugins]]
repo ='Shougo/ddu-ui-ff'

[[plugins]]
# コード補完
repo ='Shougo/ddc-around'

[[plugins]]
# コード補完
repo ='Shougo/ddc-matcher_head'

[[plugins]]
# コード補完
repo ='Shougo/ddc-sorter_rank'

[[plugins]]
# Ruby向けにendを自動挿入してくれるプラグイン
repo = 'tpope/vim-endwise'

[[plugins]]
# ステータスラインをいい感じにする
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
# ddcを動かすのに必要
repo ='vim-denops/denops.vim'
